"""交易日志端口；应用层不依赖 SQLite 实现细节。"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol, runtime_checkable

from okx_quant.domain.orders import SystemMode


@runtime_checkable
class JournalRepository(Protocol):
    """生产应用服务共同依赖的 durable journal 能力集合。"""

    path: Path

    def integrity_check(self) -> bool: ...
    def health_check(self) -> bool: ...
    def add_write_observer(self, *args: Any, **kwargs: Any) -> Any: ...
    def backup(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_mode(self) -> SystemMode: ...
    def get_mode_state(self) -> tuple[SystemMode, int]: ...
    def set_mode(self, *args: Any, **kwargs: Any) -> bool: ...
    def record_event(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_events(self, *args: Any, **kwargs: Any) -> list[dict]: ...
    def enqueue_outbox(self, *args: Any, **kwargs: Any) -> str: ...
    def enqueue_outbox_once(self, *args: Any, **kwargs: Any) -> str: ...
    def get_unpublished_outbox(self, *args: Any, **kwargs: Any) -> list[dict]: ...
    def mark_outbox_published(self, *args: Any, **kwargs: Any) -> Any: ...

    def create_decision(self, *args: Any, **kwargs: Any) -> str: ...
    def has_decision(self, *args: Any, **kwargs: Any) -> bool: ...
    def get_candle_watermark(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_candle_watermark(self, *args: Any, **kwargs: Any) -> Any: ...

    def create_order_intent(self, *args: Any, **kwargs: Any) -> Any: ...
    def update_intent(self, *args: Any, **kwargs: Any) -> Any: ...
    def find_intent(self, *args: Any, **kwargs: Any) -> Any: ...
    def apply_exchange_order(self, *args: Any, **kwargs: Any) -> Any: ...
    def import_external_order(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_nonterminal_intents(self, *args: Any, **kwargs: Any) -> list: ...
    def has_nonterminal_intent(self, *args: Any, **kwargs: Any) -> bool: ...
    def recent_intent_count(self, *args: Any, **kwargs: Any) -> int: ...
    def intent_state_counts(self, *args: Any, **kwargs: Any) -> dict: ...

    def active_reserved_quote(self, *args: Any, **kwargs: Any) -> Any: ...
    def active_reserved_instruments(
        self,
        *args: Any,
        **kwargs: Any,
    ) -> set[str]: ...
    def record_account_snapshot(self, *args: Any, **kwargs: Any) -> Any: ...
    def latest_account_snapshot(self, *args: Any, **kwargs: Any) -> Any: ...
    def account_equities_since(self, *args: Any, **kwargs: Any) -> list: ...
    def realized_pnl_since(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_position(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_positions(self, *args: Any, **kwargs: Any) -> list[dict]: ...
    def reconcile_position(self, *args: Any, **kwargs: Any) -> Any: ...
    def rebuild_position_projection(
        self,
        *args: Any,
        **kwargs: Any,
    ) -> dict: ...

    def create_protection(self, *args: Any, **kwargs: Any) -> Any: ...
    def update_protection(self, *args: Any, **kwargs: Any) -> Any: ...
    def find_protection(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_protections(self, *args: Any, **kwargs: Any) -> list: ...
    def has_active_protection(self, *args: Any, **kwargs: Any) -> bool: ...
    def acquire_exit_lease(self, *args: Any, **kwargs: Any) -> bool: ...
    def owns_exit_lease(self, *args: Any, **kwargs: Any) -> bool: ...
    def release_exit_lease(self, *args: Any, **kwargs: Any) -> Any: ...

    def start_reconciliation(self, *args: Any, **kwargs: Any) -> str: ...
    def finish_reconciliation(self, *args: Any, **kwargs: Any) -> Any: ...
    def enqueue_control_command(self, *args: Any, **kwargs: Any) -> str: ...
    def get_control_command(self, *args: Any, **kwargs: Any) -> Any: ...
    def claim_control_commands(self, *args: Any, **kwargs: Any) -> list[dict]: ...
    def finish_control_command(self, *args: Any, **kwargs: Any) -> Any: ...
